### ISSUE TITLE
Is it possible to configure this plugin to support automatic jsx runtime?

### ISSUE THREAD

**Issue by xzilja** [privatenumber/esbuild-loader#100]
Ever since react 17 was release, following became optional when using jsx elements
```js
import React from "react";
```

I looked around, it seems esbuild supports it via injection https://github.com/evanw/esbuild/issues/334 and babel supported it via `@babel/preset-react` runtime option.

is it possible to achieve this using `esbuild-loader` plugin?

**Comment by privatenumber** [comment]
The inject option isn't available in esbuild's transform API (which is what this loader uses).

In Webpack, you can use the [ProvidePlugin](https://webpack.js.org/plugins/provide-plugin/)

Related: https://github.com/privatenumber/esbuild-loader/issues/92

**Comment by xzilja** [comment]
Alright, thank you
