### ISSUE TITLE
 inject  JSX helpers in options

### ISSUE THREAD

**Issue by gozeon** [privatenumber/esbuild-loader#106]
```js
{
  jsxInject: `import React from 'react'`,
  loader: 'jsx', 
  ...
}
```

**Comment by xzilja** [comment]
This would be nice, as since typescript 4.2 a warning is thrown when importing React saying  `'React' is declared but its value is never read`

Related stackoverflow issue
https://stackoverflow.com/questions/66358237/react-is-declared-but-its-value-is-never-read-in-ts-4-2?noredirect=1#comment117315694_66358237

**Comment by privatenumber** [comment]
Webpack has a built-in solution for this via [ProvidePlugin](https://webpack.js.org/plugins/provide-plugin/).

**Comment by deleonio** [comment]
Hello together, that is not the same!

`import {h, Fragment} from 'preact';` ?!

```js
plugins: [
  new webpack.ProvidePlugin({
    '{h, Fragment}': 'preact'
  })
]
```

![image](https://user-images.githubusercontent.com/6279703/111913525-cc169600-8a6e-11eb-8974-ed5ef42e487f.png)

**Comment by gozeon** [comment]
> Hello together, that is not the same!
> 
> `import {h, Fragment} from 'preact';` ?!
> 
> ```js
> plugins: [
>   new webpack.ProvidePlugin({
>     '{h, Fragment}': 'preact'
>   })
> ]
> ```
> 
> ![image](https://user-images.githubusercontent.com/6279703/111913525-cc169600-8a6e-11eb-8974-ed5ef42e487f.png)

```js
{
   loader: 'jsx',
   jsxFactory: 'Preact.createElement' // or Preact.h
}
```

**Comment by deleonio** [comment]
Hi @gozeon 

thats not the same, too.

jsxInject enabled to remove all for JSX needed React or Preact imports.

Take a Look at vite or snowpack

**Comment by privatenumber** [comment]
@deleonio 

Consider opening a question in Discussions for configuration help with Preact. This thread is originally about React, and Provide Plugin is demonstrated to be a valid solution [here](https://github.com/privatenumber/esbuild-loader-examples/blob/d9a60599cf954a8b7e8facccb90eee9fb5d7d548/examples/react/webpack.config.js#L39-L41). Make sure your goal and blockers are clearly communicated.

This is a closed thread so it doesn't get much visibility. Not to mention, no one has provided a clear description of the problem so it's not great for discoverability either.
