### ISSUE TITLE
How to customize the jsxFactory

### ISSUE THREAD

**Issue by IWANABETHATGUY** [privatenumber/esbuild-loader#113]
## Additional context

With `rollup-plugin-esbuild` , we can do this to compat with vue jsx,
```js
import vueJsx from 'rollup-plugin-vue-jsx-compat'
import esbuild from 'rollup-plugin-esbuild'

export default {
  // ...
  plugins: [
    vueJsx(),
    esbuild({
      jsxFactory: "vueJsxCompat",
    }),
  ],
}
```
 how can i do this in esbuild-plugin, how to customize the jsxFactory

**Comment by privatenumber** [comment]
There's a `jsxFactory` option in esbuild-loader too.

Documented [here](https://github.com/privatenumber/esbuild-loader#loader).
