### ISSUE TITLE
Error after NPM configuration

### ISSUE THREAD

**Issue by zhusjfaker** [privatenumber/esbuild-loader#12]
![image](https://user-images.githubusercontent.com/31839470/88358647-5d2f5300-cda2-11ea-92a1-0e807aba3a8d.png)

![image](https://user-images.githubusercontent.com/31839470/88358664-746e4080-cda2-11ea-9aa6-191028f172a8.png)

ESBuildPlugin is already first in webpack-config

**Comment by privatenumber** [comment]
There isn't enough context in this issue for me to start debugging this, but I'm assuming this is the bug you fixed via https://github.com/egoist/esbuild-loader/commit/501f2baa95269f4d3abcb14ae408fda6a31c0858 ?
