### ISSUE TITLE
Plugins support

### ISSUE THREAD

**Issue by zmaoo** [privatenumber/esbuild-loader#120]
## Is your feature request related to a problem? Please describe.

i want to modify my source code during esbuild-loader work. 

## Describe the solution you'd like

provide an option named plugins like what babel-loader does.

**Comment by privatenumber** [comment]
Thanks for the issue @zmaoo 

What source code changes do you want to make and which plugins would you add?

**Comment by noahlaux** [comment]
fx using [esbuild-plugin-babel](https://github.com/nativew/esbuild-plugin-babel) would be nice!

**Comment by zmaoo** [comment]
> ESBuild plugins (including `esbuild-plugin-babel`) are only supported with the build API, not the transform API, which is what this loader uses. If you want to run Babel transforms that ESBuild doesn't support natively, you'll most likely want to configure `babel-loader` in series to `esbuild-loader`.

i am using babel-loader now. but it is too slow so i want to use esbuild-loader.If it doesn't support transform API, I will continue to use babel-loader

**Comment by privatenumber** [comment]
If you can tell me what transformations you're applying via Babel, maybe I can give you a better recommendation:

> What source code changes do you want to make and which plugins would you add?

**Comment by zmaoo** [comment]
> If you can tell me what transformations you're applying via Babel, maybe I can give you a better recommendation:
> 
> > What source code changes do you want to make and which plugins would you add?

i want to wrap a function(it's a global function, used for translate) to all strings that include chinese characters.i can't just replace source code as string, so i need to use ast transformers.

**Comment by privatenumber** [comment]
If I've understood what you're trying to do correctly, I think it's possible.

You can [detect all Chinese characters with regexp](https://stackoverflow.com/questions/21109011/javascript-unicode-string-chinese-character-but-no-punctuation): 

```js
/\p{Script=Han}/u.test('你好')
// true
```

So, you can write a loader that does something like:
```js
module.exports = function myCustomLoader(source) {
    // Say source is:
    // 'console.log("你好");'

	// returns 'console.log(yourFunction("你好"));'
	return source.replaceAll(
		/(["'])(\p{Script=Han}+)\1/gu,
		'yourFunction($1$2$1)'
	);
}

```

If you want sourcemap support, you can use [magic-string](https://github.com/Rich-Harris/magic-string) to manipulate the source code string.


---


Closing this as it's no longer relevant to esbuild-loader, but happy to continue the discussion here.

**Comment by gajus** [comment]
I am stuck on this issue too... I need functionality equivalent to [Relay plugin for esbuild](https://gist.github.com/sciyoshi/34e5865f2523848f0d60b4cdd49382ee).
