### ISSUE TITLE
Missing CSS files in bundle

### ISSUE THREAD

**Issue by ranisalt** [privatenumber/esbuild-loader#124]
## Bug description

I changed my webpack config to use `esbuild-loader` instead of `ts-loader` and, when doing that (see how below), all CSS is now missing. The JS bundle is apparently OK.

I also notice that after the change, webpack reports no CSS assets.

## Reproduction steps

Webpack config diff:

```diff
module.exports = {
	entry: './src/index.tsx',
	plugins: [
		new CleanWebpackPlugin(),
		new HtmlWebpackPlugin({
			base: '/',
			inject: false,
			template: 'src/index.html',
			title,
		}),
+		new ESBuildPlugin(),
		new MiniCssExtractPlugin(),
+		new ProvidePlugin({
+			React: 'react',
+		}),
		new GenerateSW(),
	],
	output: {
		filename: '[name].[contenthash].js',
		path: path.resolve(__dirname, 'dist'),
		publicPath: '/',
	},
	devtool: 'inline-source-map',
	devServer: {
		compress: true,
		historyApiFallback: true,
		hot: true,
		port: 1234,
		proxy: {
			'/api': {
				target: 'http://localhost:8074',
				changeOrigin: true,
				logLevel: 'debug',
				// rewrite /api -> / when running on localhost
				pathRewrite: API_ENDPOINT === 'dev' ? {} : { '^/api': '' },
				cookieDomainRewrite: '',
				onProxyRes(proxyRes) {
					if (proxyRes.headers['set-cookie']) {
						proxyRes.headers['set-cookie'] = proxyRes.headers['set-cookie'].map(cookie =>
							cookie.replace(/secure;/i, '').replace(/samesite=none/i, 'samesite=lax')
						);
					}
				},
			},
		},
	},
	module: {
		rules: [
			{
				test: /\.css$/,
				use: [
					'cache-loader',
					MiniCssExtractPlugin.loader,
					'css-loader',
					{
						loader: 'postcss-loader',
						options: {
							postcssOptions: {
								plugins: ['postcss-import', 'postcss-url', 'tailwindcss', 'precss', 'postcss-rtl'],
							},
						},
					},
				],
			},
			{
				test: /\.tsx?$/,
				use: [
					'cache-loader',
-					'ts-loader',
+					{
+						loader: 'esbuild-loader',
+						options: { loader: 'tsx' },
+					},
				],
			},
			{
				test: /\.(png|svg|jpe?g|gif|eot|ttf|woff2?)$/,
				type: 'asset/resource',
			},
		],
	},
};
```

## Environment

- esbuild-loader version: 2.9.2
- Webpack version: 5.25.0
- Operating System: Arch Linux
- Node version: 15.11.0
- Package manager (npm/yarn/pnpm) and version: yarn 1.22.10

**Comment by ranisalt** [comment]
I also checked the build, which turns `--mode=production` too, and it outputs some CSS, but not all. Notably, CSS that resides in a separate package (it's a monorepo) is missing, but the CSS residing in the same package works fine.

**Comment by privatenumber** [comment]
Thanks for the issue @ranisalt 

I tried reproducing your bug [here](https://github.com/privatenumber/esbuild-loader-examples/compare/124?expand=1) but it seems to work fine.

Your Webpack has a lot of extra configs that can be interfering. Can you provide a _minimal_ reproduction repo of the bug?

**Comment by ranisalt** [comment]
@privatenumber I'll try to reproduce it starting from your example

**Comment by ranisalt** [comment]
@privatenumber I am actually getting the same result *sometimes* with `ts-loader` too, so it might not be an issue with `esbuild-loader` but with webpack itself

**Comment by ranisalt** [comment]
Indeed, there is a problem when mixing `cache-loader` with other CSS loaders.

**Removing cache-loader from CSS files fixes this problem**
