### ISSUE TITLE
[doc]: `target` should be an Array, not a String

### ISSUE THREAD

**Issue by scinos** [privatenumber/esbuild-loader#128]
## Bug description

The [doc](https://github.com/privatenumber/esbuild-loader#minifyplugin) for `MinifyPlugin` says
 
> `target` `String` (`esnext`) - Environment target (e.g. `es2016`, `chrome80`, `esnext`)

But when I try to pass a string like

```
new ESBuildMinifyPlugin( {
    target: 'chrome88,edge88,firefox85,safari13.1'
} ),
```

it fails with

```
-- inner error --
Error: Transform failed with 1 error:
/Users/sergio/src/automattic/wp-calypso/node_modules/esbuild/lib/main.js:185:10: error: Invalid target: chrome88,edge88,firefox85,safari13.1
    at failureErrorWithLog (/Users/sergio/src/automattic/wp-calypso/node_modules/esbuild/lib/main.js:1195:15)
    at /Users/sergio/src/automattic/wp-calypso/node_modules/esbuild/lib/main.js:1090:24
    at /Users/sergio/src/automattic/wp-calypso/node_modules/esbuild/lib/main.js:566:9
    at handleIncomingPacket (/Users/sergio/src/automattic/wp-calypso/node_modules/esbuild/lib/main.js:655:9)
    at Socket.readFromStdout (/Users/sergio/src/automattic/wp-calypso/node_modules/esbuild/lib/main.js:533:7)
    ...
```

Looks like passing an array (`target: ['chrome88', 'edge88', 'firefox85', 'safari13.1']`) fixes the problem. This seems to match with `esbuild` JS API: https://esbuild.github.io/api/#target

## Reproduction steps

Create a webpack config and use a string with commas as target:

```
new ESBuildMinifyPlugin( {
    target: 'chrome88,edge88,firefox85,safari13.1'
} ),
```

## Environment

- esbuild-loader version: 2.10.0
- Webpack version: 5.24.4
- Operating System: OSX 10.15.7
- Node version: 12.21.0
- Package manager (npm/yarn/pnpm) and version: yarn 1.22.10

**Comment by privatenumber** [comment]
Good catch @scinos 

It can be a string if you only have one target. I mentioned the `Array<String>` type.
