### ISSUE TITLE
Add initial benchmark to compare against babel-loader based approach

### ISSUE THREAD

**Issue by bebraw** [privatenumber/esbuild-loader#13]
It would be cool to see the impact against babel-loader. I wonder if there's some open source project that could be used for figuring out the performance difference. Also pros/cons would be good to understand. At least we would lose any Babel plugins with esbuild but that's not a big deal for some projects.

**Comment by Nickhoyer** [comment]
The improvement in my project has been around 45 sec build time -> 6 sec build time in github actions, going from babel-loader to esbuild-loader

**Comment by bebraw** [comment]
@Nickhoyer That's impressive!

**Comment by privatenumber** [comment]
I took minification benchmarks here:
https://github.com/privatenumber/minification-benchmarks

In a proprietary codebase I have access to, it reduces build-time by 2~3min (7m → 4m) by replacing babel-loader and Terser with esbuild.

If you know of any large public codebases that transpiles using babel-loader and has a pretty minimal Webpack config, let me know and I can test there. I tried it on [vue-hackernews-2.0](https://github.com/vuejs/vue-hackernews-2.0) but the codebase is too small and was seeing only about a 1s difference (7s → 6s).

---

We can also make an issue/PR to add a esbuild option to Vue CLI that uses this.

**Comment by josteph** [comment]
Sharing my result on one of my CRA based, medium sized project.

**Before**
![image](https://user-images.githubusercontent.com/13672022/103356764-30673080-4ae4-11eb-8612-5380ab107f71.png)

**After**
![image](https://user-images.githubusercontent.com/13672022/103356768-32c98a80-4ae4-11eb-8cf6-a85a8707a84f.png)

Tested on:
CPU 2,3 GHz Intel Core i5
RAM 16 GB 2133 MHz LPDDR3

Though it could benefit more in a slower machine.

**Comment by khasky** [comment]
Not related to babel, but my results for medium-sized project with bundle size of 6MB are:

- Parcel 1.x ~ 50-70s
- Webpack + esbuild-loader ~ 13s

**Comment by przemuh** [comment]
In my case:

babel-loader + thread-loader - 87s
esbuild-loader - 42s

**Comment by fkhadra** [comment]
In my case, bundle size of 15MB(yes huge...). CRA ejected config

- babel: ~190 sec (cold start no cache), 90 sec with the cache
- esbuild-loader: ~55 sec 

![dev-build](https://user-images.githubusercontent.com/5574267/107863194-7426b700-6e52-11eb-8be3-b131984cb619.png)

**Comment by s-kris** [comment]
My nextjs project's build time went from 150s to 70s

**Comment by pavelloz** [comment]
Does anyone have example commit migrating from babel-loader to esbuild-loader?
Im following readme but i observe no change in speed. Before 5.5sec, after 5.5sec.

**Comment by privatenumber** [comment]
@pavelloz Please use Discussions to ask for help. There's also an [examples repo](https://github.com/privatenumber/esbuild-loader-examples) linked in the README.
