### ISSUE TITLE
Add support for query strings in webpack asset names

### ISSUE THREAD

**Issue by rowanoulton** [privatenumber/esbuild-loader#144]
## Is your feature request related to a problem? Please describe.

We're unable to use esbuild as our minifier because we make liberal use of query strings in our webpack asset names.

## Describe the solution you'd like

As per @pavelloz's suggestion in #129, we'd like to amend [this regex](https://github.com/privatenumber/esbuild-loader/blob/develop/src/minify-plugin.ts#L35) to accommodate assets with query strings attached.

## Describe alternatives you've considered

None, but we're open to alternatives!

## Additional context

While the use of query strings in asset names may seem unconventional, it's a useful tool for us to manage cache entries in our service workers for the Slack desktop client.

We attach a key, `?key=<build-identifier>`, to every asset and the service worker references them when it caches entries. This lets us match API responses with the appropriate code, to use during the next boot.

These query strings don't make it to the file system, of course, but webpack retains them internally and includes them at runtime when it makes requests.

I'm a big fan of this project and would be happy to pitch in with PRs if it's welcome.

**Comment by privatenumber** [comment]
Ah interesting. So you're importing the assets with a query `?key=<build-identifier>` within your source code built by Webpack? eg.
```js
import File from './file.js?key=123'
```

Do you mind elaborating on this part?

> These query strings don't make it to the file system, of course, but webpack retains them internally and includes them at runtime when it makes requests.

I'm wondering if the query string isn't actually a part of the file name, why support for it needs to be added to this plugin.

**Comment by pavelloz** [comment]
Its not part of the filename. In url you access it by filename.js, query param is optional and still points to the same file as filename.js?x=y

**Comment by privatenumber** [comment]
I looked at your repo again @pavelloz and it seems like I was misled by the Webpack config.

I was under the impression that Webpack would create a file with the query in the name, after all, the configuration is called `output.filename`, and the value contains a query string (`[name].js?key=[hash]`). This is why I kept saying that's not how query strings work. Instead, Webpack omits the query from the actual filename, but keeps it in the code when requesting the file. **(Wish this part was made clear in both of your requests.)**

I think that's a confusing API on Webpack's end. Wondering if there are docs for it. Where did you learn about this behavior?

Sorry for the confusion @pavelloz 

Happy to support the behavior -- PR welcome

**Comment by privatenumber** [comment]
Closed via https://github.com/privatenumber/esbuild-loader/pull/146

LMK if you guys find docs on the querystring behavior. I'd like to look deeper into it.

**Comment by pavelloz** [comment]
At the end of the day probably the best place to decide what should be done with a certain file is `test` value where loader is used.

```
+         test: /\.js$/,
+         loader: 'esbuild-loader',
```

Seems like it is configurable enough so everybody can decide what to put through the loader.

**Comment by privatenumber** [comment]
FYI this is the minification plugin, not the loader, which has a different configuration.

The include/excludes can be configured instead, but there still needs to be a default check on esbuild-loader's end that guards against misconfiguration in include/exclude.

**Comment by pavelloz** [comment]
Great job, it works flawlessly
