### ISSUE TITLE
Need option to remove console.*

### ISSUE THREAD

**Issue by breezefeng** [privatenumber/esbuild-loader#145]
Need option to remove console.*

**Comment by privatenumber** [comment]
Sorry I don't know what this means.

Please follow the Issue template to clearly communicate your request.

**Comment by ankurk91** [comment]
@privatenumber 

esbuild has an option to remove `console.log()` statements from output.

https://github.com/evanw/esbuild/issues/28

The API looks like this. 

```js
require('esbuild').transformSync(js, {
  pure: ['console.log'],
  minify: true,
})
```

**Comment by privatenumber** [comment]
I'm not sure if you're trying to ask me for something, but FYI:

> The loader supports all Transform options from esbuild.

— https://github.com/privatenumber/esbuild-loader#loader

Locking thread because original post lacks information. If there's a feature request to make, please feel free to open another one with the requested information.
