### ISSUE TITLE
Be able to pass a custom esbuild to the loader

### ISSUE THREAD

**Issue by eliseumds** [privatenumber/esbuild-loader#148]
[esbuild](https://github.com/evanw/esbuild/releases) is iterating very quickly and releasing new versions almost every day. For some this can be great specially if they're facing a weird bug and just want to be on the edge. For the majority though, it's better to be on a more stable/tested version. I'd suggest that this loader keep shipping with a stable version of esbuild, but also allow users to install and pass a custom one like [sass-loader is doing](https://github.com/webpack-contrib/sass-loader#implementation).

Discussion started in https://github.com/privatenumber/esbuild-loader/pull/143.

**Comment by eamodio** [comment]
I would like to see this as well -- keeping up with esbuild is important imo.

**Comment by privatenumber** [comment]
I'm open to the idea of accepting a reference to the users's version of esbuild (like sass-loader does).

Thanks for your consideration for the average user.

PR welcome 👍
