### ISSUE TITLE
mini-css-extract-plugin with esbuild-loader has error 

### ISSUE THREAD

**Issue by zhusjfaker** [privatenumber/esbuild-loader#15]
![image](https://user-images.githubusercontent.com/31839470/89386810-307d2300-d734-11ea-8d8c-05685f3cd5d2.png)

![image](https://user-images.githubusercontent.com/31839470/89386836-38d55e00-d734-11ea-91c8-4b346a1dd9fe.png)

**Comment by privatenumber** [comment]
This is unrelated to Mini CSS Extract plugin.

As it says in the error message, you need to add ESBuildPlugin.

Follow the example [here](https://github.com/egoist/esbuild-loader#transpiling).

**Comment by zhusjfaker** [comment]
I have already add the ESBuildPlugin in my webpack-config

![image](https://user-images.githubusercontent.com/31839470/89389857-8ce24180-d738-11ea-8936-f9867f53951c.png)

**Comment by privatenumber** [comment]
The error is throwing because it's not detecting it.

Can you share your entire Webpack config?

**Comment by zhusjfaker** [comment]
repo:
https://github.com/zhusjfaker/esbuild-demo

webpack.base.ts
https://github.com/zhusjfaker/esbuild-demo/blob/master/build/webpack.config.base.ts

webpack.config.client.ts
https://github.com/zhusjfaker/esbuild-demo/blob/master/build/webpack.config.client.ts

express
https://github.com/zhusjfaker/esbuild-demo/blob/master/build/express.ts

**Comment by privatenumber** [comment]
Can you strip it down to create a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), and add reproduction steps?

I dug around for a bit and your use of [`oneOf`](https://github.com/zhusjfaker/esbuild-demo/blob/master/build/webpack.config.base.ts#L23) doesn't seem correct. The `less` file is being compiled to JS instead of CSS output for mini css extract plugin.

I think the root of your error is with the less file. If you comment [this out](https://github.com/zhusjfaker/esbuild-demo/blob/master/src/page.tsx#L3), it builds fine.

**Comment by zhusjfaker** [comment]
In common react applications ，'import "./index.less";' is a common way to load style resources,&nbsp;
In webpack, the dependency will be handled by CSS loader under oneof rules,&nbsp;


https://github.com/egoist/esbuild-loader/issues/16




in the issues&nbsp;


It is the smallest case that we can provide&nbsp;


repo:
https://github.com/zhusjfaker/esbuild-demo
branch:
master
command:
npm run csr






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "egoist/esbuild-loader"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月6日(星期四) 凌晨0:43
收件人:&nbsp;"egoist/esbuild-loader"<esbuild-loader@noreply.github.com&gt;;
抄送:&nbsp;"zsjax"<439453290@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [egoist/esbuild-loader] mini-css-extract-plugin with esbuild-loader has error  (#15)





 
Can you strip it down to create a minimal reproducible example, and add reproduction steps?
 
I dug around for a bit and your use of oneOf doesn't seem correct. The less file is being compiled to JS instead of CSS output for mini css extract plugin.
 
I think the root of your error is with the less file. If you comment this out, it builds fine.

**Comment by privatenumber** [comment]
Specifically, I'm suggesting you didn't configure less-loader correctly.

There's a ton you can remove from that reproduction. The majority of the configurations weren't used.

**Comment by zhusjfaker** [comment]
Maybe there are some problems in the configuration of my less loader, but if I replace the Min CSS extract plugin with a CSS file in the repo provided by me, there will still be problems,


The problem is "loader: MiniCssExtractPlugin.loader This line, if you try to remove it“ MiniCssExtractPlugin.loader The esbuild will work normally



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "egoist/esbuild-loader"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月6日(星期四) 凌晨1:02
收件人:&nbsp;"egoist/esbuild-loader"<esbuild-loader@noreply.github.com&gt;;
抄送:&nbsp;"zsjax"<439453290@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [egoist/esbuild-loader] mini-css-extract-plugin with esbuild-loader has error  (#15)





 
Specifically, I'm suggesting you didn't configure less-loader correctly.
 
There's a ton you can remove from that reproduction. The majority of the configurations weren't used.

**Comment by privatenumber** [comment]
Well, yeah that's what's throwing the error.

The question is why, and it seems like it's because of your less-loader configuration.
