### ISSUE TITLE
Bump esbuild to 0.12.x

### ISSUE THREAD

**Issue by meteorlxy** [privatenumber/esbuild-loader#179]
## Describe the solution you'd like

This is a reminder to bump esbuild to the latest version.

https://github.com/privatenumber/esbuild-loader/blob/9b9b18a820d3f2d5775e95e7d62fb03b44397b6d/package.json#L43

Latest: v0.12.9 (2021/06/25)

**Comment by waltercruz** [comment]
You can use the implementation option to load a newer esbuild!

**Comment by meteorlxy** [comment]
> You can use the implementation option to load a newer esbuild!

Then it's better to remove esbuild from dependencies, or we have to install two different versions of esbuild.

**Comment by privatenumber** [comment]
I haven't had the time for it but I do want to upgrade it.

If you need it sooner than later, feel free to open a PR with the upgrade with tests updated.
