### ISSUE TITLE
Invalid option in transform() call: "resolveExtensions" 

### ISSUE THREAD

**Issue by FurryWolfX** [privatenumber/esbuild-loader#183]
### Feature request

I need the `resolveExtensions` option.

https://esbuild.github.io/api/#resolve-extensions

```
require('esbuild').buildSync({
  entryPoints: ['app.js'],
  bundle: true,
  resolveExtensions: ['.ts', '.js'],
  outfile: 'out.js',
})
```

### Why?

Modules that don't have extension names can not be resolved

**Comment by privatenumber** [comment]
esbuild-loader only applies transformations. The bundling concerns are handled by Webpack so you can defer to the Webpack config.

https://webpack.js.org/configuration/resolve/#resolveextensions

```js
module.exports = {
  //...
  resolve: {
    extensions: ['.ts', '...'],
  },
};
```
