### ISSUE TITLE
Support React's new JSX transform

### ISSUE THREAD

**Issue by SevenOutman** [privatenumber/esbuild-loader#184]
### Feature request

React 17 came with a [new JSX transform](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) feature which allow user to omit `import React from 'react'` from components. This feature has also been added back into [`v16`](https://github.com/facebook/react/releases/tag/v16.14.0), [`v15`](https://github.com/facebook/react/releases/tag/v15.7.0) and [`v0.14`](https://github.com/facebook/react/releases/tag/0.14.10) then.

I moved from `ts-loader` to `esbuild-loader` for its performance. But when I want to use the new JSX transform I notice that [esbuild has not supported yet](https://github.com/evanw/esbuild/issues/334) while [TypeScript 4.1 already supports it](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#jsx-factories).

### Why?

evanw [suggested a plugin approach](https://github.com/evanw/esbuild/issues/334#issuecomment-760427837), and I believe this loader is a good place for doing it.

**Comment by privatenumber** [comment]
Evan means [esbuild plugins](https://esbuild.github.io/plugins/), not just any plugin.

esbuild-loader uses esbuild's transform API, [which doesn't support esbuild plugins](https://github.com/privatenumber/esbuild-loader#is-it-possible-to-use-esbuild-plugins).

If you want to omit the React import, you can use [Webpack's Provide Plugin](https://github.com/privatenumber/esbuild-loader#is-it-possible-to-use-esbuilds-inject-option).

Closing since this feature request belongs in esbuild rather than esbuild-loader.

**Comment by nerdyman** [comment]
For any people who want to copy and paste the solution:

```js
plugins: [
  new webpack.ProvidePlugin({
    React: 'react',
  }),
],
```

https://github.com/privatenumber/esbuild-loader-examples/blob/52ca91b8cb2080de5fc63cc6e9371abfefe1f823/examples/react/webpack.config.js#L39

**Comment by alexandernst** [comment]
esbuild implemented automatic JSX transform in 0.14.51 https://github.com/evanw/esbuild/blob/master/CHANGELOG.md#01451

Maybe reopen this?

**Comment by privatenumber** [comment]
Why does it need to be reopened if it's been implemented?

**Comment by alexandernst** [comment]
I assumed that esbuild-loader must implement something in order to pass that new option to esbuild. Maybe this is not the case and the current implementation can already be used. If this is the case, how can I pass that option?

**Comment by alexandernst** [comment]
Nevermind, I found it. For anyone that might get here from google search, this is the config:

```
{
  test: /\.jsx?$/,
  exclude: /node_modules/,
  use: [
    {
      loader: "esbuild-loader",
      options: {
        loader: 'jsx',
        target: 'es2015',
        jsx: 'automatic',  // <--- this is the new option 
      }
    },
  ]
},
```

Using this new option renders this unnecessary: 

```
plugins: [
  new webpack.ProvidePlugin({  // <-- can be removed
    React: 'react',            // <-- can be removed
  }),                          // <-- can be removed
],
```


@privatenumber Maybe [this section of the docs](https://github.com/privatenumber/esbuild-loader#is-it-possible-to-use-esbuilds-inject-option) should be updated in order to reflect this.

**Comment by privatenumber** [comment]
PR welcome on this example:
https://github.com/privatenumber/esbuild-loader-examples/blob/52ca91b8cb2080de5fc63cc6e9371abfefe1f823/examples/react/webpack.config.js#L39-L41

**Comment by alexandernst** [comment]
https://github.com/privatenumber/esbuild-loader-examples/pull/6

**Comment by mwalkerr** [comment]
I'm on version `2.19.0` which is the latest at the time of writing this, but attempting to use `jsx: 'automatic'` results in:

```
Module build failed (from ./node_modules/.pnpm/esbuild-loader@2.19.0_webpack@5.73.0/node_modules/esbuild-loader/dist/index.js):
Error: Invalid value "automatic" in "--jsx=automatic"
```
Trying to use `jsxImportSource` similarly fails:
```
node_modules/.pnpm/esbuild@0.14.48/node_modules/esbuild/lib/main.js:241:12: ERROR: Invalid option in transform() call: "jsxImportSource"
```

**Comment by privatenumber** [comment]
Make sure you're using the latest esbuild via https://github.com/privatenumber/esbuild-loader/#bring-your-own-esbuild-advanced

**Comment by mwalkerr** [comment]
Thank you @privatenumber, that worked. Apologies for missing what was already in the docs!

**Comment by robwierzbowski** [comment]
Note that adding `automatic` in the code in https://github.com/esbuild-kit/esbuild-loader/issues/184#issuecomment-1214217036 does not implement the new JSX transform, but automates adding the old transform's required import. See   https://github.com/evanw/esbuild/issues/334 for more information.

**Comment by privatenumber** [comment]
Can you elaborate? The latest comment in the thread you referenced says `--jsx=automatic` works now.

**Comment by robwierzbowski** [comment]
Automatic adds the current `import React from ‘react’;` import, but if you read the issue and the ones around it you’ll see it doesn’t use the new transform, which also requires changing the function signature of the imported JSX transformer. The maintainers of esbuild mention that changing the function signature is very complex, and they aren’t addressing it right now. 

If you look at Vite with EsBuild, they give the option of using the new transform via loading a plugin that runs babel and the React supplied transformer, greatly increasing build times. There is no way to use the new transform with EsBuild at this time.

**Comment by robwierzbowski** [comment]
Would be happy to be wrong though! I spent the day digging through issues and docs on this today.

**Comment by privatenumber** [comment]
What are you referring to as the old & new JSX transforms?

**Comment by robwierzbowski** [comment]
New: see the description of this PR, “react 17 came with a new JSX transform”, and related blog post linked to on React’s blog. 

Old: the previous method of transforming JSX, which leveraged `import React from ‘react’`.

**Comment by robwierzbowski** [comment]
The documentation for the JSX automatic option also mentions the old transform style, and doesn’t mention the new transform style. 

https://esbuild.github.io/content-types/#auto-import-for-jsx

**Comment by privatenumber** [comment]
I just wanted to ensure we're on the same page regarding the old and new JSX transforms, as you seem quite confident about esbuild not supporting a feature that many others claim it does.

Using the [same input from the React blog](https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#:~:text=Let%E2%80%99s%20say%20that%20your%20source%20code%20looks%20like%20this%3A), you can [verify esbuild outputs the new transform](https://hyrious.me/esbuild-repl/?version=0.15.5&mode=transform&input=export+default+function+Profile%28%29+%7B%0A++return+%28%0A++++%3Ch1%3EHello%3C%2Fh1%3E%0A++%29%0A%7D%0A&options=--loader%3Djsx+--jsx%3Dautomatic+).

If you still have concerns or encounter issues with this feature, I would recommend discussing them directly on the relevant GitHub issue: https://github.com/evanw/esbuild/issues/334.

**Comment by RyanzpLee** [comment]
On esbuild-loader 3.0.1 the `jsx: 'automatic'` option is not available anymore. What is the recommended method of enabling automatic jsx import?

**Comment by privatenumber** [comment]
If it doesn't work you can file a bug with a demonstration that it's not working.

Locking this thread as the original issue has been resolved, and the rest are all debugging help. If you need help, post in Discussions instead.
