### ISSUE TITLE
Minify bundle

### ISSUE THREAD

**Issue by egoist** [privatenumber/esbuild-loader#2]

**Comment by i5ting** [comment]
手是真快。牛逼

**Comment by egoist** [comment]
@i5ting Interested in contributing? 😄

**Comment by privatenumber** [comment]
I might be interested in helping add minification.

It's going to have to be a plugin though, and I'm not sure if it makes sense to add it to a package suffixed `-loader` (although I suppose `vue-loader` does).

What do you think?

**Comment by egoist** [comment]
@privatenumber this loader already uses a plugin to start esbuild service: https://github.com/egoist/esbuild-loader/blob/master/src/index.js#L42

**Comment by privatenumber** [comment]
Looks like it's been done https://github.com/sorrycc/esbuild-webpack-plugin
