### ISSUE TITLE
Missing sourcemaps

### ISSUE THREAD

**Issue by fgarcia** [privatenumber/esbuild-loader#242]
### Bug description

When I replace babel-loader with esbuild-loader my project did run as normal, except that my browser no longer finds sourcemaps

### Reproduction

My loader config is:
```
{
      test: /\.tsx?$/,
      loader: 'esbuild-loader',
      options: {
        loader: 'tsx',
        target: 'es2015',
        jsxFactory: '_jsx',
        sourcemap: true, // tried with and without this line
      }
},
```

My webpack devtool source map style is set to the recommended one for development (eval-source-map)

### Node.js package manager

npm

### Environment

```shell
System:
    OS: Linux 5.13 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 3.15 GB / 15.39 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
From the [documentation](https://github.com/privatenumber/esbuild-loader#:~:text=source-maps%20are%20automatically%20configured%20for%20you%20via%20devtool.%20sourcemap%2Fsourcefile%20options%20are%20ignored.):
> Source-maps are automatically configured for you via [devtool](https://webpack.js.org/configuration/devtool/). sourcemap/sourcefile options are ignored.

If you're still encountering the bug, please provide a minimal reproduction.

**Comment by narueon** [comment]
I am facing the same issue. what are the various options that are supported? it is from 
esbuild https://esbuild.github.io/api/#sourcemap
or 
webpack https://webpack.js.org/configuration/devtool/#devtool

**Comment by privatenumber** [comment]
Webpack devtool. It's linked in my comment above.

**Comment by shaulgo** [comment]
I have the same problem.
1. app's source maps load
2. lib's source maps don't load

**Comment by privatenumber** [comment]
From the comment above:

> If you're still encountering the bug, please provide a minimal reproduction.

Feel free seek help in [Discussions](https://github.com/privatenumber/esbuild-loader/discussions).
