### ISSUE TITLE
When I use ts loader in vue2 project, I get error: 'error: panic: Unexpected expression of type <nil>'

### ISSUE THREAD

**Issue by xyj404** [privatenumber/esbuild-loader#253]
### Bug description

Syntax Error: Error: Transform failed with 1 error:
error: panic: Unexpected expression of type <nil> (while printing "/Users/**/**.ts")

### Reproduction

vue2 vuex-module-decorators webpack4 vuex

### Node.js package manager

npm

### Environment

```shell
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 88.09 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.5 - ~/emsdk/node/14.15.5_64bit/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/emsdk/node/14.15.5_64bit/bin/npm
  npmPackages:
    esbuild-loader: ^2.18.0 => 2.18.0
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
Thanks for the issue.

There's no information in this issue for me to understand where the error is coming from.

Can you please provide reproduction?

Happy to re-open issue when provided.
