### ISSUE TITLE
Transforming async generator functions to the configured target environment ("es2015") is not supported yet

### ISSUE THREAD

**Issue by swamm007** [privatenumber/esbuild-loader#259]
### Bug description

Hi!

I am using esbuild-loader for my project with async generator functions,  But it will report compilation error.

Transforming async generator functions to the configured target environment ("es2015") is not supported yet.

The code in question is as follows
`
async function* request(initIndex = 0) {
    ......
  }
`
Are there any plans to support async generator functions in the future?

### Reproduction

`async function* request(initIndex = 0) {
    ......
  }`

### Node.js package manager

npm

### Environment

```shell
esbuild-loader version: 2.19.0,
Webpack version: 4.41.4
Operating System: macOS 11.3.1
Node version: 12.18.3
Package manager (npm/yarn/pnpm) and version: npm 6.14.6
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
If 2015 is too low, have you tried setting a higher target?
```
target: 'es2018'
```

**Comment by swamm007** [comment]
> If 2015 is too low, have you tried setting a higher target?
> 
> ```
> target: 'es2018'
> ```

Thanks, the problem is solved after the target is changed to es2108
