### ISSUE TITLE
Support Transform Imports

### ISSUE THREAD

**Issue by ghost** [privatenumber/esbuild-loader#260]
### Feature request

We use esbuild-loader in our applications and it works like a charm. 

The only issue we are facing is that it is missing a key feature - Transform Imports

Reference:
https://mui.com/zh/material-ui/guides/minimizing-bundle-size/

### Why?

It's quite important to support this feature for reduing the bundle size of MUI packages and Lodash.

There are a few esbuild plugins can do the samething, but there's no way to use plugins with this loader.

I would recommend to add this feature to the plugin by default, otherwise our bundle size would be doubled.

As I know some people has already done something there:
https://github.com/privatenumber/esbuild-loader/pull/256

Is it possible to continue the work?

Thanks
CJ

**Comment by privatenumber** [comment]
Sounds out of scope to support this in esbuild-loader which is just a esbuild wrapper.

You can consider opening a feature request with [esbuild](https://github.com/evanw/esbuild).

Alternatively, you can find or make a Webpack loader that makes that change, and just chain them.

**Comment by richardchen85** [comment]
@cjapra https://github.com/olajs/transform-imports-loader this repo should be help
