### ISSUE TITLE
Breaking version dependency esbuild@0.14.51

### ISSUE THREAD

**Issue by itutto** [privatenumber/esbuild-loader#266]
### Bug description

Files loaded with `esbuild-loader` no longer recognise JSX syntax and webpack build fails.

```
99% done plugins webpack-hot-middlewarewebpack built preview bd9e9555c49d48aa3473 in 13570ms
ModuleParseError: Module parse failed: Unexpected token (24:37)
File was processed with these loaders:
 * ./node_modules/esbuild-loader/dist/index.js
You may need an additional loader to handle the result of these loaders.
```

### Reproduction

I have been using the `esbuild-loader` plugin in webpack to load `.js` files that contain JSX react code. 

```js
test: /\.js$/,
  use: [
    {
      loader: 'esbuild-loader',
      options: { loader: 'jsx', target: 'es6' }
    }
  ],
```
It was working perfectly until today, when the `esbuild` package version was bumped to `0.14.51` from `0.14.49`.

The loader now no longer recognises JSX syntax and webpack reports to find the an appropriate loader.
If I lock the version of `esbuild` to 0.14.49 then it is working again. 

### Node.js package manager

npm

### Environment

```shell
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 646.06 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.5.3 - /usr/local/bin/npm
  npmPackages:
    esbuild-loader: ^2.19.0 => 2.19.0 
    webpack: ^5.64.3 => 5.74.0
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
Can you provide a link to a minimal reproduction?

**Comment by itutto** [comment]
> Can you provide a link to a minimal reproduction?

Sure, it will take some time though.

**Comment by privatenumber** [comment]
Will re-open when provided.

**Comment by deini** [comment]
Leaving this here in case it helps anyone 👀 

We had the same issue and it was a config mistake in our side, in out `tsconfig.json` we had:

```json
"jsx": "preserve"
```

Starting in `0.14.51` esbuild respects the tsconfig's `jsx` flag which didn't transform `jsx` and thats why webpack was complaining it requires additional loaders.

More info on https://github.com/evanw/esbuild/releases/tag/v0.14.51
