### ISSUE TITLE
Webpack "magic comments" do not work in Worker constructors

### ISSUE THREAD

**Issue by benjamind** [privatenumber/esbuild-loader#267]
### Bug description

Worker constructors don't work with magic comments so chunks cannot be easily named.

```js
new Worker(
        /* webpackChunkName: "foo-worker" */ new URL(
            "../foo-worker.ts",
            import.meta.url
        ),
        { type: "module" }
    );
```

Filed a separate ticket on esbuild project where this needs to be fixed: https://github.com/evanw/esbuild/issues/2439

### Reproduction

Use the following syntax to load a worker with a webpack chunk name magic comment:

```js
new Worker(
        /* webpackChunkName: "foo-worker" */ new URL(
            "../foo-worker.ts",
            import.meta.url
        ),
        { type: "module" }
    );
```

Note that the worker chunk does not have the name correctly applied.

### Node.js package manager

npm

### Environment

```shell
Any
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
Fixed in https://github.com/evanw/esbuild/releases/tag/v0.15.17
