### ISSUE TITLE
Issue with typescript namespace

### ISSUE THREAD

**Issue by ynifamily3** [privatenumber/esbuild-loader#268]
### Bug description

Here's an example you can reproduce.
https://github.com/ynifamily3/esbuild-loader-issue

index.ts
```typescript
import { NS } from "./types";
import B = NS.A;

function x(a: B) {
  console.log(a.message);
}

x({ message: "Hello" });
```

types.ts
```typescript
export namespace NS {
  export interface A {
    message: string;
  }
}
```

When trying to bundle, I see an error.
`TypeError: Cannot read properties of undefined (reading 'A')` 

### Reproduction

Clone this [this](https://github.com/ynifamily3/esbuild-loader-issue) repo
Run `npm i`
Run `npm run build` # using ts-loader
Run `npm run start`
You should see a working node app.
Run `npm run build:esbuild` # using esbuild-loader
Run `npm run start`
You should see an error.

### Node.js package manager

npm

### Environment

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz
    Memory: 16.01 GB / 31.86 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.4 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    esbuild-loader: ^2.19.0 => 2.19.0
    webpack: ^5.74.0 => 5.74.0
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
Can you use:
```ts
import type { NS } from "./types";
```

**Comment by ynifamily3** [comment]
@privatenumber A ts(1380) error occurs. :(

**Comment by privatenumber** [comment]
I think this is the same issue as https://github.com/esbuild-kit/tsx/issues/83

It's an esbuild issue so I'm closing this and redirecting conversation here:
https://github.com/evanw/esbuild/issues/2468
