### ISSUE TITLE
Esbuild failed to compress CSS

### ISSUE THREAD

**Issue by peacejj** [privatenumber/esbuild-loader#270]
### Bug description

echo 'div { box-shadow: 0 0 8px rgba(0, 0, 0, 0.15) \9 }' | esbuild --loader=css --minify
div{box-shadow: 0 0 8px rgba(0,0,0,.15) \  }

This is a syntax error in antd 4.17.1  (adding \9), which can be ignored in CSS, but after ESBuild compression, the 9 is gone, leaving \, causing subsequent style parsing errors.

The result I want is \9 reserved, as this will not cause a conflict

### Reproduction

echo 'div { box-shadow: 0 0 8px rgba(0, 0, 0, 0.15) \9 }' | esbuild --loader=css --minify

### Node.js package manager

npm

### Environment

```shell
node10及以上
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by peacejj** [comment]
@privatenumber please~

**Comment by privatenumber** [comment]
Sounds like an esbuild issue than an esbuild-loader issue.

Please file it with esbuild: https://github.com/evanw/esbuild

**Comment by evanw** [comment]
I was curious about this so I looked into it. This doesn't even seem like a bug to me. Relevant parts from [the CSS specification](https://www.w3.org/TR/css-syntax-3/#consume-token):

> ### § 4.3.1. Consume a token
> **U+005C REVERSE SOLIDUS (\)**
> If the input stream [starts with a valid escape](https://www.w3.org/TR/css-syntax-3/#check-if-two-code-points-are-a-valid-escape), [reconsume the current input code point](https://www.w3.org/TR/css-syntax-3/#reconsume-the-current-input-code-point), [consume an ident-like token](https://www.w3.org/TR/css-syntax-3/#consume-an-ident-like-token), and return it.

> ### § 4.3.8. Check if two code points are a valid escape
> If the first [code point](https://infra.spec.whatwg.org/#code-point) is not U+005C REVERSE SOLIDUS (\), return false.
> Otherwise, if the second [code point](https://infra.spec.whatwg.org/#code-point) is a [newline](https://www.w3.org/TR/css-syntax-3/#newline), return false.
> Otherwise, return true.

> ### § 4.3.11. Consume an ident sequence
> Let result initially be an empty string.
> Repeatedly consume the [next input code point](https://www.w3.org/TR/css-syntax-3/#next-input-code-point) from the stream:
> * [ident code point](https://www.w3.org/TR/css-syntax-3/#ident-code-point)
>     Append the [code point](https://infra.spec.whatwg.org/#code-point) to result. 
> * the stream [starts with a valid escape](https://www.w3.org/TR/css-syntax-3/#check-if-two-code-points-are-a-valid-escape)
>     [Consume an escaped code point](https://www.w3.org/TR/css-syntax-3/#consume-an-escaped-code-point). Append the returned [code point](https://infra.spec.whatwg.org/#code-point) to result. 
> * anything else
>     [Reconsume the current input code point](https://www.w3.org/TR/css-syntax-3/#reconsume-the-current-input-code-point). Return result.

> ### § 4.3.7. Consume an escaped code point
> Consume the [next input code point](https://www.w3.org/TR/css-syntax-3/#next-input-code-point).
> * [hex digit](https://www.w3.org/TR/css-syntax-3/#hex-digit)
>     Consume as many [hex digits](https://www.w3.org/TR/css-syntax-3/#hex-digit) as possible, but no more than 5. Note that this means 1-6 hex digits have been consumed in total. If the [next input code point](https://www.w3.org/TR/css-syntax-3/#next-input-code-point) is [whitespace](https://www.w3.org/TR/css-syntax-3/#whitespace), consume it as well. Interpret the hex digits as a hexadecimal number. If this number is zero, or is for a [surrogate](https://infra.spec.whatwg.org/#surrogate), or is greater than the [maximum allowed code point](https://www.w3.org/TR/css-syntax-3/#maximum-allowed-code-point), return U+FFFD REPLACEMENT CHARACTER (�). Otherwise, return the [code point](https://infra.spec.whatwg.org/#code-point) with that value. 
> * EOF
>     This is a [parse error](https://www.w3.org/TR/css-syntax-3/#parse-error). Return U+FFFD REPLACEMENT CHARACTER (�). 
> * anything else
>     Return the [current input code point](https://www.w3.org/TR/css-syntax-3/#current-input-code-point).

So basically `\9` is a valid CSS ident token consisting of a single tab character, and is correctly parsed by esbuild as such. Then when esbuild prints it out, esbuild has to escape the tab character because an unescaped tab character is not a valid ident token. In CSS any character can be escaped as an ident by putting a backslash before it, so esbuild just puts a backslash before the tab character to make it a valid ident. If this is causing further CSS processing problems later on then I believe it's a bug in whatever other CSS parser you're using, not in esbuild.
