### ISSUE TITLE
Adding TypeScript declaration file

### ISSUE THREAD

**Issue by egoist** [privatenumber/esbuild-loader#28]

**Comment by privatenumber** [comment]
I don't use an IDE with type hints but would this mainly be for the benefit of that?

(I don't imagine esbuild-loader to be apart of a Typescript compilation.)

**Comment by herberthobregon** [comment]
You can write all `loader` in TS, and in `prepare` script after push to NPM convert to JS with *.map an *.d.ts files. This is the good practice 🚀

This loader is amazing! congratulations!

**Comment by reslear** [comment]
yes please add declaration file

**Comment by privatenumber** [comment]
This is WIP but is being implemented for type checking purposes.

Type-checking and practice aside, I'm still curious why this is in demand. Is it just for your IDE code completions when configuring the loader?

**Comment by reslear** [comment]
@privatenumber yes for vscode, 

1. so as not to write @ts-ignore
<img width="884" alt="Снимок экрана 2020-11-16 в 14 41 06" src="https://user-images.githubusercontent.com/12596485/99248593-c4718700-2819-11eb-8336-a3db0f77ace3.png">
else get errors, and not compile bundle
<img width="847" alt="Снимок экрана 2020-11-16 в 14 46 34" src="https://user-images.githubusercontent.com/12596485/99249147-a8bab080-281a-11eb-9988-4ff763b0d74b.png">


2. have auto suggestions for example, get types 
<img width="575" alt="Снимок экрана 2020-11-16 в 14 43 48" src="https://user-images.githubusercontent.com/12596485/99248824-26ca8780-281a-11eb-87cc-da7fbce1f222.png">

3. ts on hype 😄

**Comment by privatenumber** [comment]
Types added in v2.6.0.
