### ISSUE TITLE
Bump loader-utils version due to critical error

### ISSUE THREAD

**Issue by ornic** [privatenumber/esbuild-loader#285]
### Feature request

Now package-lock shows **^2.0.0** version of **loader-utils**

```
    "node_modules/esbuild-loader": {
      "version": "2.20.0",
      "resolved": "https://registry.npmjs.org/esbuild-loader/-/esbuild-loader-2.20.0.tgz",
      "integrity": "sha512-dr+j8O4w5RvqZ7I4PPB4EIyVTd679EBQnMm+JBB7av+vu05Zpje2IpK5N3ld1VWa+WxrInIbNFAg093+E1aRsA==",
      "dev": true,
      "dependencies": {
        "esbuild": "^0.15.6",
        "joycon": "^3.0.1",
        "json5": "^2.2.0",
        "loader-utils": "^2.0.0",
        "tapable": "^2.2.0",
        "webpack-sources": "^2.2.0"
      },
      "funding": {
        "url": "https://github.com/privatenumber/esbuild-loader?sponsor=1"
      },
      "peerDependencies": {
        "webpack": "^4.40.0 || ^5.0.0"
      }
    },
```

Please bump version to **^2.0.3**

### Why?

There is a critical error in versions prior to **2.0.3**: https://github.com/advisories/GHSA-76p3-8jx3-jpfq

**Comment by kenny128** [comment]
There are CVE around loader-utils now too
https://www.npmjs.com/advisories/1084992 
https://www.npmjs.com/advisories/1084995

**Comment by privatenumber** [comment]
Note, these `npm audit` reports about dev tooling don't have any real consequence (because they don't accept public input) and it's just creating work for others to spin their wheels.
https://overreacted.io/npm-audit-broken-by-design/

In any case, PR welcome.

**Comment by privatenumber** [comment]
I just looked at this closer, and this is an issue with your `package-lock.json`.

Run `npm update` and your nested dependencies should upgrade within the semver ranges.

I tried locally on a project with `esbuild-loader` and there are no issues:
```
$ npm audit
found 0 vulnerabilities
```
