### ISSUE TITLE
Upgrade `esbuild` to 0.16

### ISSUE THREAD

**Issue by tony-scio** [privatenumber/esbuild-loader#290]
### Feature request

See https://github.com/evanw/esbuild/releases/tag/v0.16.0 for breaking changes.

### Why?

Keep dependencies up to date.

**Comment by privatenumber** [comment]
I usually avoid upgrading _just because_ there's a new version. But @MonkBen provided a good reason [here](https://github.com/privatenumber/esbuild-loader/pull/288#issuecomment-1369974648): 

> Any update on when this can be merged in? I would like to test esbuild-loader but am unable to. There is a https://github.com/evanw/esbuild/issues/2761 that was [recently fixed](https://github.com/evanw/esbuild/commit/46347f78f503a364eb5fc56d214a4fdb85be0324) and I can't test out esbuild-loader until it is in as a third party library I am using exposes this defect.


Even though esbuild-loader allows a custom esbuild to be passed in, it's good to have better defaults.
