### ISSUE TITLE
Webpack v4 API inconsistencies

### ISSUE THREAD

**Issue by issacgerges** [privatenumber/esbuild-loader#298]
### Bug description

There are some issues with this package that can cause problems when used with `webpack@4`
* The explicit dependency on `webpack-sources` will bring in an additional version on most versions of webpack. These sources are passed back into the webpack compilation
   * In `webpack` v5, these source classes are available via the `compiler` ([example](https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/src/index.js#L426-L427))
   * In `webpack` v4, I believe an explicit dependency is needed on `webpack-sources@1.4.3` to match the version used by `webpck/webpack`
* `sourceAndMap` is not consistently present on compilation sources in `v4`. This code should use `sourceAndMap` when available and fallback to a `null` map and `source.source()` ([example](https://github.com/webpack-contrib/terser-webpack-plugin/blob/v4.2.3/src/index.js#L258-L278))

### Reproduction

n/a

### Node.js package manager

npm

### Environment

```shell
npmPackages:
  webpack: 4.x
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
I really appreciate this issue. Thanks for the feedback @issacgerges.

RE: First bullet
I think you're definitely right. Will fix.

RE: Second bullet
Do you have an example where `sourceAndMap` will not be present in Webpack 4? So far, it hasn't been a problem for me, and I feel like I'd be getting bug reports if it wasn't available. In any case, if it's possible, I'd like to cover it in a test.

**Comment by issacgerges** [comment]
No worries! I know one example is that plugins can (and sometimes do) manually add assets to the compilation, here's [one](https://github.com/dojo/webpack-contrib/blob/master/src/emit-all-plugin/EmitAllPlugin.ts#L16-L19) such example, those usually only satisfy `source` and `size`. I'm actually no longer confident you can even rely on this in `webpack@5`. Even `webpack` does [similar checks](https://github.com/webpack/webpack/blob/2403a36326248f7f515959a479baa257288bef4d/lib/EvalSourceMapDevToolPlugin.js#L109-L120) internally

**Comment by privatenumber** [comment]
Thanks @issacgerges !
Should be covered now.
