### ISSUE TITLE
Document `DefinePlugin` alternative

### ISSUE THREAD

**Issue by privatenumber** [privatenumber/esbuild-loader#315]
### Feature request

Esbuild can be used as an alternative to [`DefinePlugin`](https://webpack.js.org/plugins/define-plugin/).

Document usage.

### Why?

n/a

**Comment by Sparkenstein** [comment]
Was looking for this, I am facing issue with esbuild-loader with my webpack. DefinePlugin does not get loaded before esbuild I guess, so build fails. 
How can I use esbuild as defineplugin?

**Comment by mirekmts** [comment]
I  was using webpack DefinePlugin in the project. I wanted to support older browsers and encountered this problem.

The solution is to add a define section to `esbuild-loader`.

Before
```
rules: [
           ....
       {
            test: //.(ts|tsx)$/,
            exclude: /node_modules/,
            loader: "esbuild-loader",
            options: {
                loader: "tsx",
                target: 'esnext'
            },
       }
]

plugins: [
        ....
        new webpack.DefinePlugin({
            "import.meta.env.MODE": JSON.stringify(process.env.NODE_ENV),
            "import.meta.env.PATH": JSON.stringify('path'),
        }),
]
```
After 
```
rules: [
           ....
       {
            test: //.(ts|tsx)$/,
            exclude: /node_modules/,
            loader: "esbuild-loader",
            options: {
                loader: "tsx",
                target: 'es2015'
                define: {
                    "import.meta.env.MODE": JSON.stringify(process.env.NODE_ENV),
                    "import.meta.env.PATH": JSON.stringify('path'),
                }
           },
       }
]
```

**Comment by privatenumber** [comment]
Nice, it should use the plugin instead of the loader though so it catches variables in the entire app. For example, `process.env.NODE_ENV` is often used in dependencies and when you use the loader, node modules are typically excluded. Also, these replacements are best used with minification so the minifier can remove blocks that are unused `if (process.env.NODE_ENV === 'development')`.


Would you mind opening a PR to document?

**Comment by privatenumber** [comment]
Closed via https://github.com/esbuild-kit/esbuild-loader/commit/fb8548547d5f95cc8d0848e0af0fb47fd2c42307
