### ISSUE TITLE
Esbuild throws errors on generic arrow functions in certain cases

### ISSUE THREAD

**Issue by charliematters** [privatenumber/esbuild-loader#322]
### Bug description

We have upgraded esbuild-loader to avoid the node 18 bug in webpack, and suddenly we are getting syntax errors which are not being reported by tsc.

It seems that it can no longer parse this line:
```typescript
const foo = async <T>(bar:T): Promise<T> => bar
```

The error thrown is `Expected ")" but found ":"`

I've added a repo which shows that when that file is consumed from stdin it fails, but passing the filename as an argument works as expected

### Minimal reproduction link

https://github.com/charliematters/esbuild-issue

### Environment

```shell
TODO
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by charliematters** [comment]
This is the wrong repo - I'll move it

**Comment by privatenumber** [comment]
You didn't tell esbuild that the input is TypeScript.

Works fine when you do: https://hyrious.me/esbuild-repl/?version=0.17.16&mode=transform&input=const+foo+%3D+async+%3CT%3E%28bar%3AT%29%3A+Promise%3CT%3E+%3D%3E+bar&options=--loader%3Dts


Also, if you recently upgraded esbuild-loader to v3, see the migration guide:
https://github.com/esbuild-kit/esbuild-loader/releases/tag/v3.0.0
