### ISSUE TITLE
Doesn't work well with esbuild 0.18.x and inherited `tsconfig.json` and `experimentalDecorators`

### ISSUE THREAD

**Issue by eamodio** [privatenumber/esbuild-loader#325]
### Bug description

esbuild 0.18.x changed how esbuild uses tsconfig files: https://github.com/evanw/esbuild/releases/tag/v0.18.0

Which seems to conflict or somehow interfere with how this plugin parses the `tsconfig.json`. Can we now just pass the `tsconfig.json` file provided directly to esbuild?

### Minimal reproduction link

https://github.com/gitkraken/vscode-gitlens

### Environment

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 14.34 GB / 31.92 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    esbuild-loader: 3.0.1 => 3.0.1
    webpack: 5.86.0 => 5.86.0
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
I'm not sure I understand what you're reporting. There's no description of the problem and how it differs from the expected behavior. Is there an error you're getting?

Closing until minimal reproduction is provided.

**Comment by eamodio** [comment]
Sorry the issues I'm experiencing are more of a side effect of esbuild-loader parsing tsconfig itself rather than passing the file path directly to rebuild (which is now supported in 0.18.x)

**Comment by privatenumber** [comment]
It's not possible to pass in the tsconfig file path to the esbuild Transform API.

**Comment by eamodio** [comment]
Damn, I see that now. And I think I've figured out the issue -- its related to the caching of `fileMatcher` in https://github.com/esbuild-kit/esbuild-loader/blob/3ee8b5765aa229cf46c28898a8c22a71d9f5e6e4/src/loader.ts#L51-L73

In my parallel webpack build, it seems to be reusing a cached version for a different `tsconfig.json`. Still working on digging through it, but if I change that single cache to a `Map` based on the `tsconfigPath` then it resolves the issue.

**Comment by eamodio** [comment]
Opened https://github.com/esbuild-kit/esbuild-loader/pull/327 to resolve this. Technically didn't have anything to do with decorators or the esbuild upgrade, they just exposed the issue.
