### ISSUE TITLE
esbuild 0.18

### ISSUE THREAD

**Issue by silverwind** [privatenumber/esbuild-loader#326]
### Feature request

esbuild 0.18 has been out for a while, it should be upgraded. As far as I can tell, it should be a smooth upgrade with little breaking changes.

https://github.com/evanw/esbuild/blob/main/CHANGELOG.md

### Why?

Keep up with latest features and bug fixes.

**Comment by eamodio** [comment]
Should support passing the `tsconfig.json` file path directly to esbuild
https://github.com/evanw/esbuild/blob/main/CHANGELOG.md#0180

Refs: https://github.com/esbuild-kit/esbuild-loader/issues/325

**Comment by privatenumber** [comment]
@eamodio I'm hiding your comment because it's irrelevant to the issue.

FYI if anyone needs esbuild upgraded, PR welcome 👍
