### ISSUE TITLE
sourceMappingURL getting removed by minifier

### ISSUE THREAD

**Issue by Rishi500** [privatenumber/esbuild-loader#329]
### Bug description

Issue: In webpack v4. sourceMappingURL has legal comment //#
example: //# sourceMappingURL: xyz.chunk.js.map

As per esbuild docs, it does not consider //# as a legal comment hence it is getting removed during minification.

### Minimal reproduction link

NA

### Environment

```shell
this is not environment specific.
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
Not really sure what you mean. Can you provide a minimal reproduction?

Happy to reopen once the bug is demonstrated.
