### ISSUE TITLE
enable esbuild-loader with relay plugin

### ISSUE THREAD

**Issue by sibelius** [privatenumber/esbuild-loader#332]
### Feature request

Can I use this plugin 

https://gist.github.com/sciyoshi/34e5865f2523848f0d60b4cdd49382ee

to compile graphql tags needed for relay

### Why?

without this we get this error

```
graphql: Unexpected invocation at runtime. Either the Babel transform was not set up, or it failed to identify this call site. Make sure it is being used verbatim as `graphql`. Note also that there cannot be a space between graphql and the backtick that follows.
```

### Alternatives

What is the best way to do this ?

**Comment by privatenumber** [comment]
Nope. Explanation: https://github.com/esbuild-kit/esbuild-loader#is-it-possible-to-use-esbuild-plugins

However, that esbuild plugin is doing a pretty simple code transformation so you can easily implement that as a Webpack loader yourself. Or perhaps there's an existing Webpack loader that does the same thing.

I don't use GraphQL so I'm not sure what that code is doing, but maybe this is similar: https://github.com/samsarahq/graphql-loader
