### ISSUE TITLE
Define property prevents bundle from minifying

### ISSUE THREAD

**Issue by pavel-krasnov** [privatenumber/esbuild-loader#337]
### Problem

Given the provided template, I run npm start and get a minified bundle under the dist folder.

- I add the following to replace values in the bundle:

```
new EsbuildPlugin({
  define: {
    'process.env.ENV': JSON.stringify('value'),
  },
}),
```

- I run npm start and get a _not_ minified bundle under the dist folder.

It looks like using EsbuildPlugin to define values prevents minification no matter what.

### Expected behavior

The bundle is minified when I use EsbuildPlugin with define.

### Minimal reproduction URL

https://stackblitz.com/edit/node-gme7l3

### Version

4.0.0

### Node.js version

16.20.0

### Package manager

npm

### Operating system

Linux

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
Thanks, and good catch!

Really appreciate the reproduction. Fix coming soon.
