### ISSUE TITLE
ngDevMode is not defined, when building Angular 15.2 or higher

### ISSUE THREAD

**Issue by vzakharov-rxnt** [privatenumber/esbuild-loader#339]
### Problem

After upgrading from prior 15.2 to 15.2 or later (including latest 16.x), I am getting `ngDevMode is not defined` error on app load. The error is terminating, app does not load.

I am using custom webpack plugin and esbuild-loader to build my app.

I reproduced the issue using standard Angular boilerplate project here:

- https://ng-esbuild-minify.netlify.app/
- https://github.com/vzakharov-rxnt/ng-esbuild-minify

To prove that it works fine in 15.1, I created a branch where the issue is fixed, and opened a PR to merge. Only package.json was changed, downgrading Angular to 15.1. PR triggers CI build, so you can confirm that the issue is indeed fixed:

- https://github.com/vzakharov-rxnt/ng-esbuild-minify/pull/1
- https://deploy-preview-1--ng-esbuild-minify.netlify.app/

[Angular team rejected my ticket as unsupported](https://github.com/angular/angular-cli/issues/25830), apparently they don't support custom webpack at all.

Relevant bits of the custom webpack config, if commented out, the build works fine.

```
const { EsbuildPlugin } = require("esbuild-loader");
//...

if (options.optimization) {
  // https://how-to.dev/how-to-speed-up-angular-cli-app-with-esbuild-loader
  // remove 2 first minimizers, hoping they are the TerserPlugin
  config.optimization.minimizer.shift();
  config.optimization.minimizer.shift();

  config.optimization.minimizer.unshift(
    new EsbuildPlugin(),
  );
}
```

### Expected behavior

If Angular CLI can minify it without build or startup errors, so should the EsbuildPlugin.

### Minimal reproduction URL

https://ng-esbuild-minify.netlify.app/

### Version

"esbuild-loader": "4.0.2",

### Node.js version

v18.17.1

### Package manager

npm

### Operating system

Windows

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by JeanMeche** [comment]
You can already do what you want be defining `ngDevMode` in a similar way the Angular CLI does it : 

    new EsbuildPlugin({
       define: { ngDevMode: "undefined" },
    })

The current CLI implementation for reference : https://github.com/angular/angular-cli/blob/6a97d41b7d8c4cdecaf1b6d57f730a2e5ac326d8/packages/angular_devkit/build_angular/src/tools/esbuild/application-code-bundle.ts#L261

**Comment by vzakharov-rxnt** [comment]
It worked! Thank you, @JeanMeche.
I am surprised Angular team rejected the issue with such a simple solution.
