### ISSUE TITLE
Module resolution problems

### ISSUE THREAD

**Issue by thorn0** [privatenumber/esbuild-loader#342]
### Problem

This package doesn't play well with TypeScript when `moduleResolution` is set to `NodeNext`.

See https://arethetypeswrong.github.io/?p=esbuild-loader%404.0.2 for a detailed explanation of the problem.

Possible solutions:
1) remove `"type": "module"` from `package.json`
2) or rename `dist/index.d.ts` -> `dist/index.d.cts`

### Expected behavior

I expected this line
```
import { EsbuildPlugin } from "esbuild-loader";
```
to keep working after I changed the `moduleResolution` option in `tsconfig.json` from `Node` to `NodeNext`.

For now we use a dynamic import as a workaround.

### Minimal reproduction URL

https://stackblitz.com/edit/node-1zhtpc?file=foo.ts&view=editor

### Version

4.0.2

### Node.js version

16+

### Package manager

npm

### Operating system

Windows

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
I see why it's technically not correct, but I'd like to make sure I'm seeing the same problem first.

In your reproduction, I'm still able to get the correct types when I add:
```
import { EsbuildPlugin } from "esbuild-loader";
```

<img width="1029" alt="Screenshot 2023-10-11 at 1 20 41 PM" src="https://github.com/privatenumber/esbuild-loader/assets/1075694/86242857-7538-434d-9c72-5f0797c3a956">

**Comment by thorn0** [comment]
Try this in a `.ts` CommonJS module, not in `.js`. That's why there is the `foo.ts` file in my reproduce.

**Comment by privatenumber** [comment]
Whys it imported from a `.ts` file? It's designed to be imported from a Webpack config file

FYI Setting `"allowJs": true` works too

**Comment by thorn0** [comment]
webpack is a library. CLI is not the only way to use it.

**Comment by privatenumber** [comment]
Could've just said "I'm using Webpack via Node rather than the CLI" instead of the snarky response.

Feel free to submit a PR.
