### ISSUE TITLE
Only 1 plugin working at a time

### ISSUE THREAD

**Issue by gpoitch** [privatenumber/esbuild-loader#344]
### Problem

If I have multiple plugin instances, only 1 of them applies.
```js
{ 
  plugins: [
    new EsbuildPlugin({
      define: {
        __TEST__: JSON.stringify(true),
      },
    }),
    new EsbuildPlugin({
      define: {
        __TEST2__: JSON.stringify(false),
      },
    }),
  ],

  optimization: {
    minimize: true,
    minimizer: [
      // Use esbuild to minify
      new EsbuildPlugin()
    ]
  }
}
```

Here only the first define plugin works. Not the second or the minimizer.
I wouldn't actually use 2 plugins for define, it's just to help illustrate the issue. If I only use one, then the minimizer plugin doesn't apply for example.

### Expected behavior

All plugins apply correctly, or document that you can only use 1 and provide some alternate way to use the minifier.

### Minimal reproduction URL

https://stackblitz.com/edit/node-d2twym

### Version

4.0.2

### Node.js version

20.7.0

### Package manager

npm

### Operating system

macOS

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by gpoitch** [comment]
My current solution is to only use the plugin for minification purposes and `define`s can be set as loader options.

**Comment by privatenumber** [comment]
Not sure how, but this seems to have been inadvertently fixed via https://github.com/privatenumber/esbuild-loader/releases/tag/v4.0.2

Testing on your reproduction with the new esbuild-loader no longer produces the bug.

I also added a test here to verify: https://github.com/privatenumber/esbuild-loader/commit/b9e5b2a8b0369a6a97d28cc5800bd3505e26cd95
