### ISSUE TITLE
Float's optimization

### ISSUE THREAD

**Issue by merrytoaster** [privatenumber/esbuild-loader#349]
### Problem

1.  Setting up a simple webpack config
```
 const path = require("path");

module.exports = {
  entry: "./src/index.js",
  mode: "production",
  output: {
    filename: "main.js",
    path: path.resolve(__dirname, "dist"),
  },
  optimization: {
    minimize: false
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: "esbuild-loader",
        options: {
          target: "es2016",
        },
      },
    ],
  },
};
```
main.js
`import 'core-js/actual';`

2. Build the project

3. Open dist/main.js and go to the line #10523 
`var nativeToFixed = uncurryThis(1 .toFixed);`

How this line looks in source code:` var nativeToFixed = uncurryThis(1.0.toFixed);`

The number float is gone and there's a space

When I use **cloudflare** server then server optimizes js and gives modified js without some spaces ie:
`var nativeToFixed = uncurryThis(1.toFixed);`

The expression `1.toFixed` causes an error `Invalid or unexpected token`

Two solutions to this problem 
fix the loader or fix the server. Started with you

### Expected behavior

The source code
` var nativeToFixed = uncurryThis(1.0.toFixed);`
 should be builded as 
`var nativeToFixed = uncurryThis(1..toFixed);`

### Minimal reproduction URL

https://stackblitz.com/edit/stackblitz-starters-larnfb?file=webpack.config.js

### Version

^4.0.2

### Node.js version

v16.18.1

### Package manager

npm

### Operating system

Windows

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
As the README says, esbuild-loader is a wrapper for [esbuild](https://github.com/evanw/esbuild), which handles the transformation.

And looks like there's no esbuild bug here. The output yields identical output as the input:
<img width="319" src="https://github.com/privatenumber/esbuild-loader/assets/1075694/e56e9c33-4e15-46a2-85b8-c62629498b83">
