### ISSUE TITLE
Enable "dynamic-import" by default

### ISSUE THREAD

**Issue by neoGeneva** [privatenumber/esbuild-loader#360]
### Feature request

I think it would be a good idea to set `supported: { "dynamic-import": true }` in the options sent to transform by default.

### Motivations

The problem is that Webpack's code splitting uses dynamic imports for splitting, and if you're targeting browsers that don't support dynamic imports then esbuild will switch out `import()` for `require()` which breaks the code splitting, and results in the files being bundled together.

I believe this is a low risk change, since Webpack will handle the transforms of those `import()` calls, so esbuild doesn't need to be translating them.

### Alternatives

Alternatively it'd be good to have something in `README.md` to note that setting is enabled.

### Contributions

- [X] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
Good catch! Thanks for the PR

Adding a reproduction for reference:
https://esbuild.github.io/try/#dAAwLjIwLjEALS10YXJnZXQ9Y2hyb21lNTIAaW1wb3J0KCdhYmMnKQ
