### ISSUE TITLE
Optional Chaining does not work in webpack 4

### ISSUE THREAD

**Issue by bnainar** [privatenumber/esbuild-loader#370]
### Problem

I've included a simple reproduction in stackblitz below
In esbuild loader options, setting target >= es2020 results in following error, but builds successfully in < es2020
```
❯ npm run build

> build
> webpack

Hash: 9380bee32a4ebff16d97
Version: webpack 4.47.0
Time: 319ms
Built at: 05/05/2024 00:14:24
  Asset      Size  Chunks             Chunk Names
main.js  4.17 KiB    main  [emitted]  main
Entrypoint main = main.js
[./src/index.js] 391 bytes {main} [built] [failed] [1 error]

ERROR in ./src/index.js 4:12
Module parse failed: Unexpected token (4:12)
File was processed with these loaders:
 * ./node_modules/esbuild-loader/dist/index.cjs
You may need an additional loader to handle the result of these loaders.
| import { render } from "react-dom";
| const x = {};
> const y = x?.a?.a;
| render(/* @__PURE__ */ jsx("div", {}), document.getElementById("root"));
```

### Expected behavior

Same as in webpack v5 - Optional chaining should not throw errors and should not require any additional plugins

### Minimal reproduction URL

https://stackblitz.com/edit/node-qf9n3j?file=webpack.config.js

### Version
```json
{
  "scripts": {
    "build": "webpack"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "esbuild-loader": "^4.1.0",
    "webpack": "^4.47.0",
    "webpack-cli": "^4.10.0"
  }
}
```

### Node.js version

v18

### Package manager

npm

### Operating system

macOS

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
If Webpack is not compatible with operational chaining and throwing an error, why not file the issue with Webpack?

**Comment by bnainar** [comment]
Oh you are right. Thanks! (https://stackoverflow.com/a/59972726)
