### ISSUE TITLE
Why not upgrade esbuild?

### ISSUE THREAD

**Issue by harrisyangbo** [privatenumber/esbuild-loader#373]
### Feature request

"esbuild v0.21 now supports decorators in JavaScript, should we consider upgrading?"

### Motivations

My current project uses vue-cli2 with webpack4 as the build tool. The current build speed is too slow, so I want to optimize it using esbuild-loader. However, esbuild-loader does not support decorators which are used in many parts of my project. The latest version of esbuild, however, does support decorators.

### Alternatives

no other idea

### Contributions

- [X] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
Feel free to open a PR

**Comment by silverwind** [comment]
https://github.com/privatenumber/esbuild-loader/pull/374
