### ISSUE TITLE
Error: File '@ljharb/tsconfig' not found.

### ISSUE THREAD

**Issue by Piero87** [privatenumber/esbuild-loader#376]
### Problem

Hello, I open a bug report because the discussion page is disabled for this project, I have the same problem: https://github.com/privatenumber/esbuild-loader/issues/363 and also this problem happen only with pnpm and not with yarn 4.0.0, there any solution to fix it?

### Expected behavior

that is working with pnpm

### Minimal reproduction URL

sorry don't have it it's related to other issue

### Version

4.2.0

### Node.js version

v20.15.0

### Package manager

pnpm

### Operating system

macOS

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
https://github.com/privatenumber/esbuild-loader/issues/363#issuecomment-1997166180

Discussion is available for sponsors. If you're a sponsor, I'll be happy to support you there.
