### ISSUE TITLE
Does esbuild-loader have a configuration like babel-plugin-import that can be imported on demand

### ISSUE THREAD

**Issue by IsDyh01** [privatenumber/esbuild-loader#379]
### Feature request

Does esbuild-loader have a configuration like babel-plugin-import that can be imported on demand

### Motivations

I want to use esbuild-loader in webpack to compile files, but also want to import component libraries like antd on demand

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
Hi, this is a bug tracker. Please direct your questions to the sponsors-only Discussions: https://github.com/pvtnbr/esbuild-loader/discussions

**Comment by IsDyh01** [comment]
Sorry，open the url as 404

**Comment by privatenumber** [comment]
It's for sponsors only. Once you become a sponsor, you'll be able to access it: https://github.com/sponsors/privatenumber
