### ISSUE TITLE
使用ESBuildMinifyPlugin  后treeshaking失效了

### ISSUE THREAD

**Issue by Versatile4396** [privatenumber/esbuild-loader#380]
### Problem

在vue2 项目中使用ESBuildMinifyPlugin压缩优化产物导致了有内容treeshaking失效，切换成terser 则不会有问题，有人遇到过类似的问题吗

### Expected behavior

在vue2 项目中使用ESBuildMinifyPlugin压缩优化产物导致了有内容treeshaking失效，切换成terser 则不会有问题，有人遇到过类似的问题吗

### Minimal reproduction URL

none

### Version

1

### Node.js version

1

### Package manager

yarn

### Operating system

macOS

### Contributions

- [X] I plan to open a pull request for this issue
- [X] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
This is an esbuild issue:
https://github.com/evanw/esbuild/issues/3570
