### ISSUE TITLE
Target when using 'minifySyntax' option with minifyer plugin

### ISSUE THREAD

**Issue by asbjornh** [privatenumber/esbuild-loader#41]
We just discovered that when using `minifySyntax` option for the `ESBuildMinifyPlugin` nullish coalescing operators ( `??`) are output which we don't want. Is there a way of setting a target so that for instance only ES5-compatible transforms are performed when minifying syntax?

**Comment by privatenumber** [comment]
Yeah, even though it's called "MinifyPlugin", it actually [passes in all options to esbuild](https://github.com/egoist/esbuild-loader/blob/esbuild-peer-dependency/src/minify-plugin.js#L96), so you can pass any esbuild option in:

```js
new ESBuildMinifyPlugin({
    target: 'es2015'
})
```

I plan on renaming it to EsBuildPlugin in the next major to support this use-case.

**Comment by asbjornh** [comment]
Cool! Thanks for clearing that up 🙂
