### ISSUE TITLE
Spread options in loader

### ISSUE THREAD

**Issue by Nickhoyer** [privatenumber/esbuild-loader#44]
This is already being done in minify plugin, wouldn't it make sense to also do this in the loader?
I want to pass "platform" option, but I noticed it won't accept this in it's current state.

**Comment by privatenumber** [comment]
I can make it do a spread, but it [doesn't seem like esbuild's `transform` method accepts a `platform` option](https://github.com/evanw/esbuild/blob/758b25f8e227d29aba2b4cd37351cc823e642af3/lib/common.ts#L187-L189).
