### ISSUE TITLE
[Question] Does the minify plugin support es5 as target? 

### ISSUE THREAD

**Issue by Dan1ve** [privatenumber/esbuild-loader#56]
Hi,

we use the `ESBuildMinifyPlugin` to minify our JS sources in **production** mode. The actual `esbuild-loader` is only active in **dev** mode (with `target: es2019` in case this is relevant).

What happens in our production build now is the following: The minify plugin receives ES5-compatible code and converts certain patterns back to ES6. (The specific example we saw in the final output are ES6 template literals for strings that contained `\n`).

Is there a way to avoid this behavior, so that the code will stay es5 compatible? 

I tried `minifySyntax : false`, but this doesn't seem to fix _all_ cases. Specifically, the string in `const c = '"\''` gets "minified" by wrapping it in backticks, which is not es5 compatible.

**Comment by privatenumber** [comment]
Yeah, pass in `target: 'es2015'` to the Minify plugin.

I've been meaning to add better documentation for that use-case.

**Comment by Dan1ve** [comment]
Thanks for the fast response! It's good to know that there is a `target` option for the minifier. Unfortunately, `es2015` (= ES6) won't work in our case, as we need es5 support. I tried a couple of browser-specific options such as `safari9` (as `ieX` is not available as option), but this didn't help either. The docs do mention that es6 seems to be the oldest supported version, so for time being, we'll have to switch back to terser then.

**Comment by privatenumber** [comment]
Gotcha.

FYI from the esbuild README:

> Transforming ES6+ syntax to ES5 is not supported yet. However, if you're using esbuild to transform ES5 code, you should still set --target=es5. This prevents esbuild from introducing ES6 syntax into your ES5 code. For example, without this flag the object literal {x: x} will become {x} and the string "a\nb" will become a multi-line template literal when minifying. Both of these substitutions are done because the resulting code is shorter, but the substitutions will not be performed if --target=es5 is present.

Hopefully, support for ES5 is added soon

**Comment by avennn** [comment]
Any progress about support for ES5?

**Comment by privatenumber** [comment]
Check with esbuild: https://esbuild.github.io/content-types/#es5
