### ISSUE TITLE
Support esbuild >0.8.0

### ISSUE THREAD

**Issue by Djaler** [privatenumber/esbuild-loader#63]
There are some backwards-incompatible changes in that release https://github.com/evanw/esbuild/blob/master/CHANGELOG.md#080

**Comment by privatenumber** [comment]
Thanks for the issue.

It's already [upgraded](https://github.com/privatenumber/esbuild-loader/commit/4d207a12200a9ce21458e4da2a253e7da0e9f148#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) but not yet released. Will try to cut a feature release soon.

**Comment by Djaler** [comment]
I see that you prepared a version where esbuild will be a peer dependency. That would be nice too because esbuild releases very often.

**Comment by privatenumber** [comment]
You can currently install that via `npm i esbuild-loader@next` but that's going to have to be held till esbuild reaches a stable version since they can technically add breaking changes right now that will break this loader.

**Comment by privatenumber** [comment]
@Djaler 

Just updated [esbuild to v0.8.17](https://github.com/privatenumber/esbuild-loader/blob/develop/package.json#L35) (latest) and released it in [esbuild-loader v2.5.0](https://www.npmjs.com/package/esbuild-loader/v/2.5.0)

**Comment by Djaler** [comment]
Thanks!
