### ISSUE TITLE
export 'Interface' (reexported as 'AnotherInterfaceName') was not found

### ISSUE THREAD

**Issue by olegKusov** [privatenumber/esbuild-loader#70]
Having this warnings. App don't work.

**Comment by privatenumber** [comment]
Please provide more context:
- What app?
- What tools/versions are you using?
- If there's an error, do you have a stack trace?
- Do you have screenshots?
- Do you have reproduction steps?

**Comment by olegKusov** [comment]
> Please provide more context:
> 
>     * What app?
> 
>     * What tools/versions are you using?
> 
>     * If there's an error, do you have a stack trace?
> 
>     * Do you have screenshots?
> 
>     * Do you have reproduction steps?

Im using typescript 4.1.2. 

![изображение](https://user-images.githubusercontent.com/28058268/101197843-b2923f80-3673-11eb-869d-ca898ab4785f.png)

Types files

![изображение](https://user-images.githubusercontent.com/28058268/101200376-43b6e580-3677-11eb-8ee1-2c0871f756b7.png)

**Comment by privatenumber** [comment]
This seems irrelevant to esbuild-loader... I'm closing this but feel free to open another issue if you have a specific esbuild-loader bug that you can provide reproduction steps to.

**Comment by kevcenteno** [comment]
In case anyone runs into this issue, you need to use the `type` keyword when importing/exporting types.  See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html
