### ISSUE TITLE
don't build project sometimes.

### ISSUE THREAD

**Issue by olegKusov** [privatenumber/esbuild-loader#71]
Im using latest version of esbuild-loader, react 16. Sometimes when I change something im my code, my app get white screen. And hard reload doesnt help. Only full project building helps.

**Comment by privatenumber** [comment]
Not sure if I can help debug if you don't know how to reproduce the issue consistently.

Can you work on providing a minimal reproduction codebase?

**Comment by olegKusov** [comment]
> Not sure if I can help debug if you don't know how to reproduce the issue consistently.
> 
> Can you work on providing a minimal reproduction codebase?

I need to work on it. Know I don't know how I can reproduce it.

**Comment by privatenumber** [comment]
Thanks @olegKusov !

Open a new issue when you can provide a reproduction.
