### ISSUE TITLE
Typeissue with Webpack v4 (Cannot find module 'webpack5' or its corresponding type declarations)

### ISSUE THREAD

**Issue by escapedcat** [privatenumber/esbuild-loader#72]
We're using Webpack v4 in our projekt. 
Now our typecheck fails with:
```
$ tsc --noEmit
node_modules/esbuild-loader/dist/minify-plugin.d.ts(3,27): error TS2307: Cannot find module 'webpack5' or its corresponding type declarations.
error Command failed with exit code 2.
```

Might be related to this:
https://github.com/privatenumber/esbuild-loader/blob/develop/src/minify-plugin.ts#L5-L6  

This loader seems to solve it with this: 
https://github.com/privatenumber/esbuild-loader/blob/develop/package.json#L58

I guess we could also install webpack v5. But only to fix typings this seems a bit weird.
You have any ideas how this could be solved or changed? If you can point to the right direction I'm happy to provide a PR.

**Comment by privatenumber** [comment]
Ah good catch @escapedcat 

I think the webpack5 dependency needs to be moved from `devDependencies` to `dependencies`.

It does seem excessive but that's what TypeScript needs 🤷‍♂️

**Comment by deleonio** [comment]
Esbuild-loader is a webpack extension. 

Webpack can not be a dependency of esbuild-loader. 

Webpack must be a devDep and peerDep of esbuild-loader.

Prease remove webpack from the deps.

**Comment by privatenumber** [comment]
Fixed for Webpack 4 in v2.6.3 via https://github.com/privatenumber/esbuild-loader/pull/78

[LMK if anyone has ideas](https://twitter.com/privatenumbr/status/1338787270938255361?s=20) on how to interop with Webpack v5 as well

**Comment by deleonio** [comment]
@privatenumber Thanks
@escapedcat Thanks, too

**Comment by bboydflo** [comment]
Thanks for this package. Unfortunately I am using webpack 5 and the provided types are not compatible with that :(. Have you got any feedback on how to support typescript 5 types?

**Comment by privatenumber** [comment]
@bboydflo Nope. I mentioned [here](https://github.com/privatenumber/esbuild-loader/pull/78) but ts-loader, vue-loader, and html-webpack-plugin all seem to have this limitation too.

Do you know any loaders/plugins that offer Webpack 5 type support?

**Comment by bboydflo** [comment]
I think [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin) has a beta version that works correctly with webpack 5. I fixed the issue by patching the types. It's a bit hacky but for now it's good enough for me :)

**Comment by bboydflo** [comment]
anyway I am impressed on how well this lib is designed. I haven't tested it myself with webpack 4 but it seems to work as expected with webpack 5.

esbuild supports other asset types as well, like text, images, etc. in your opinion would it make sense for esbuild-loader to act as a loader for those assets?
