### ISSUE TITLE
failed with thread-loader

### ISSUE THREAD

**Issue by Usey95** [privatenumber/esbuild-loader#80]
Hello, I've met problems using esbuild-loader together with thread-loader:
```
use: [
         'thread-loader',
        {
            loader: 'esbuild-loader',
            options: {
                loader: 'jsx', // Remove this if you're not using JSX
                target: 'esnext' // Syntax to compile to (see options below for possible values)
            }
        }
]
```
error looks like https://github.com/privatenumber/esbuild-loader/issues/16, it can't detect esbuildService:
```
Cannot read property '$esbuildService' of undefined
```
Thanks for any help :)

**Comment by privatenumber** [comment]
FYI thread-loader is for off-loading loaders with expensive operations to a separate thread/process.

Since esbuild already off-loads its operations to the esbuild process, it's unnecessary to apply thread-loader to it.

**Comment by Usey95** [comment]
> FYI thread-loader is for off-loading loaders with expensive operations to a separate thread/process.
> 
> Since esbuild already off-loads its operations to the esbuild process, it's unnecessary to apply thread-loader to it.

ah, got it. Thank you
