### ISSUE TITLE
Add test, include, and exclude options to ESBuildMinifyPlugin like the Terser Webpack plugin

### ISSUE THREAD

**Issue by raygesualdo** [privatenumber/esbuild-loader#81]
I have a complex Webpack build where we have to use Terser for one chunk (there's some very strict mangling rules we have to follow). I want to use `ESBuildMinifyPlugin` for the rest of the chunks, but without the ability to filter chunks, we'd be double-minifying the special chunk, which would break things. I dug into the Terser plugin and it seems there's some Webpack code we could use fairly straightforwardly:

https://github.com/webpack-contrib/terser-webpack-plugin/blob/809ef42f3ad128693862a535a647305702d11eb8/src/index.js#L210-L218 

The referenced Webpack helper is straightforward as well:

https://github.com/webpack/webpack/blob/2efeb4b5787e868e69233aa9dec469c200fa3b2c/lib/ModuleFilenameHelpers.js#L162-L179

**Comment by raygesualdo** [comment]
If this sounds like a good idea, I can try to get a PR up this week.

**Comment by privatenumber** [comment]
Open to a `exclude`/`include` option for `ESBuildMinifyPlugin`.

PR welcome! Thanks

**Comment by raygesualdo** [comment]
@privatenumber I PRed the changes in #82.
