### ISSUE TITLE
Support for --bundle

### ISSUE THREAD

**Issue by arcanis** [privatenumber/esbuild-loader#91]
Something I'd like to explore would be using ESBuild for JS bundling, and Webpack for "every that isn't JS" bundling. By that I mean that ESBuild would compile everything that's JS, but would leave the original imports when it detects something that it can't make sense of (for instance, that could be `.png` imports).

The result would then be a single ESM module that Webpack could parse to extract the remaining imports, transform them into JS, then pack in a final bundle. On the other hand, Webpack wouldn't have to deal with the overall JS bundling, which I would assume is a major part where ESBuild fares better.

Is it something you considered?

**Comment by privatenumber** [comment]
Right now, the primary purpose of esbuild-loader right now is to help optimize some of the bottlenecks introduced by [babel-loader](https://twitter.com/wSokra/status/1316274855042584577?s=20) and Terser.

That sounds like an interesting bundling strategy but probably something outside the scope of this project. Note, esbuild has plugin support to bundle in files esbuild can't by default, and there's projects like [esload](https://github.com/benmerckx/esload) that let you plug in Webpack loaders.

Closing this as it's not an issue. Feel free to start a Discussion if you want to talk about it more.
