### ISSUE TITLE
Exposing plugins through the build api

### ISSUE THREAD

**Issue by ismail-syed** [privatenumber/esbuild-loader#98]
👋 Thanks for sharing this awesome loader!

Are there any plans to leverage the `esbuild.build`  API over the [`esbuild.transform`](https://github.com/privatenumber/esbuild-loader/blob/develop/src/loader.ts#L33). 

Though still new an experimental, esbuild exposes the ability to extend build functionality through [plugins](https://esbuild.github.io/plugins/). As per the Plugin docs: 

> Plugins can also only be used with the build API, not with the transform API.

**Comment by privatenumber** [comment]
Nope. esbuild's build API is for bundling, which is what Webpack does. If you want to use the build API, you can call it directly w/o Webpack.

Not to mention, Webpack loaders tap into the in-memory bundling process so it's not possible to use the build API which directly accesses the file-system.
