### ISSUE TITLE
Use babel-loader and esbuild-loader in webpack at the same time

### ISSUE THREAD

**Issue by zheyaoa** [privatenumber/esbuild-loader#99]
I have a good idea is that use babel-loader and esbuild-loader both in webpack.
So I have a test is config my webpack is that 
![image](https://user-images.githubusercontent.com/31647991/105712740-30c4e100-5f55-11eb-8ec9-d2b143714b38.png)
i want to use esbuild-loader to transform code from high version code to es5.
The babel-loader only use to do some custom babel-plugin sush as babel-plugin-import and react-refresh/babel
![image](https://user-images.githubusercontent.com/31647991/105713083-a8930b80-5f55-11eb-9260-2e3ee2880a27.png)
But i get an error .
![image](https://user-images.githubusercontent.com/31647991/105713160-bea0cc00-5f55-11eb-866c-cd6bc5a225c9.png)
I don't know what happened.

**Comment by zheyaoa** [comment]
https://github.com/XHMM/webpack5-test/tree/esbuild-babel

**Comment by privatenumber** [comment]
I haven't looked into the error yet, but you should know that esbuild's main selling point is speed. 

Keeping Babel in the chain jeopardizes the speed benefit of using esbuild because [Babel is still the bottleneck](https://twitter.com/wSokra/status/1316274855042584577?s=20).

**Comment by privatenumber** [comment]
I looked into it, and turns out the source map returned by esbuild needed to be parsed first.

Thanks for reporting!
